= Java 24
:toc:
:toc-placement:
:toclevels: 3

Java 24 will be released on the 18th of March 2025, and the full list of enhancements is now available tallying up to an astounding 24 changes. This certainly doesn't raise the expectations for release 25!

Let us take a closer look at what's awaiting us!

== Core

=== https://openjdk.org/jeps/472[JEP 472: Prepare to Restrict the Use of JNI]

This JEP is geared towards issuing warnings in a consistent manner in case of JNI or FFM usage that goes against https://openjdk.org/jeps/8305968[integrity by default].
These warnings and future restrictions can be selectively disabled by enabling those specific interfaces when needed.

When using a native function we'll get a `WARNING` at startup unless we use the JVM `--enable-native-access` option to authorize it, or add the `Enable-Native-Access` manifest entry.

Using native functions without authorization is illegal, hence the aptly called `--illegal-native-access` which allows us to control the JVM's behaviour, with the default being a warning.

The options are:

* warn (default): a warning will be emitted in the JVM logs
* allow: use is authorized without restriction
* deny: use is refused, an IllegalCallerException will be thrown

Violating this will result in a warning being emitted by the JVM in the following form:

`WARNING: A restricted method in java.lang.System has been called`

=== https://openjdk.org/jeps/484[JEP 484: Class-File API]

This JEP which was initially a preview in 22 and 23 aims to provide a standard API for parsing, generating and transforming Java class files.

It is geared towards helping developers handle the swifter release cadence, and thus class-file format changes. The API would evolve alongside the class file format, which would reduce the reliance of library and framework developers on third-party developers to update and test their class-file libraries. Frameworks and libraries making use the standard API will support class files from the latest JDK automatically.

=== https://openjdk.org/jeps/485[JEP 485: Stream Gatherers]

This JEP enhances the Stream API with new intermediate operations to facilitate new data operations that previously weren't easily achievable. This will be handled by facilitating the creation of custom intermediate operations to manipulate the streams, rather than a lot of new methods of the specifically requested functions.

We're already seeing some interesting libraries pop up with useful gatherers such as https://github.com/tginsberg/gatherers4j[Gatherers4j].

=== https://openjdk.org/jeps/489[JEP 489 Vector API (Ninth Incubator)]

The ninth iteration API of an API for vector computations. It aims to be a way to express these in a manner that compiles reliably to optimal vector instructions on supported CPU architectures to achieve better performance than equivalent scalar computations.

This iteration adds a new `Float16` which supports 16-bit variables in IEEE 754 binary16 format using the Vector API.

It has also been confirmed that the API will remain in incubation until project Valhalla enters preview itself so that the API can leverage the expected performance and in-memory representation enhancements.

== HotSpot

=== https://openjdk.org/jeps/404[JEP 404: Generational Shenandoah (Experimental)]

This aims to enhance the Shenandoah GC with an experimental generational mode, without impacting non-generational.

With non-generational we mean that the heap was not split into multiple zones each containing objects of different ages. It's based upon the *Weak Generational Hypothesis* which stats that *most objects die young*. The collection of dead objects is very cheap, so if we separate the two we can target young objects to clean the heap more efficiently.

The intent is to reduce the sustained memory footprint, and reduce resource consumption. Initially it'll only support X64 and AArch64, with more instruction sets being supported later.

It was originally intended to land in JDK21. but it was dropped at that time due to identified risks (see for reference https://mail.openjdk.org/pipermail/jdk-dev/2023-June/007959.html[this jdk-dev mailing list entry]) to make sure than when it landed it would deliver the best possible result.

We can enable it through the following JVM options: `-XX:+UnlockExperimentalVMOptions -XX:ShenandoahGCMode=generational`.

== Targeted

- https://openjdk.org/jeps/450[JEP 450: Compact Object Headers (Experimental)] - Geared towards object header sizes on 64-bit architectures (x64 and AArch64) without introducing any major throughput or latency overhead.

- https://openjdk.org/jeps/475[JEP 475: Late Barrier Expansion for G1]  - Simplifies the G1 GC barrier implementation, which stores information about the application memory access by moving the expansion of the expansion thereof to later in the C2 JIT's compilation pipeline. This makes the G1 barriers more comprehensible, reduced the C2 execution time when using the G1 collector and guarantees the preservation of the C2 invariants while preserving the quality of C2 generated code.

- https://openjdk.org/jeps/479[JEP 479: Remove the Windows 32-bit x86 Port]  - As planned after the deprecation for removal in JDK 21 (JEP 449) the Windows 32 bit X86 bit source code and build support has been removed.

- https://openjdk.org/jeps/491[JEP 491: Synchronize Virtual Threads without Pinning] - which aims to improve scalability of synchronized methods & statements by making it possible for Virtual Threads that block in such cases to release their underlying platform threads. This will almost fully eliminate cases of VT being pinned to platform threads.

- https://openjdk.org/jeps/493[JEP 493: Linking Run-Time Images without JMODs] - This aims to facilitate run-time image generate from modules regardless of what those modules were (JMOD, modular JAR, part of a previously linked run-time, etc.). This will also reduce the JDK size by enabling the jlink tool to create custom images without using the JDK's JMOD files. NOTE: this feature might not be enabled by all vendors.

- https://openjdk.org/jeps/498[JEP 498: Warn upon Use of Memory-Access Methods in sun.misc.Unsafe] - Starting in JDK 24, a runtime warning will be issued upon the first invocation of any method in sun.misc.Unsafe, which has been fully deprecated, with the recommendation that developers migrate to the standard VarHandle API (JEP 193) and Foreign Function & Memory API (JEP 454) to ensure smooth transitions in future JDK releases.

== Integrated

- https://openjdk.org/jeps/483[JEP 483: Ahead-of-Time Class Loading & Linking] - This feature aims to enhance Java application startup performance by monitoring an application during one run and creating a cache of pre-loaded and pre-linked classes for subsequent runs. It seeks to improve startup time by leveraging the typically consistent startup process of applications, without requiring changes to application code, command-line usage, or build tools. The approach provides a foundation for future improvements in startup and warmup time, with the current implementation focusing on caching classes loaded by built-in class loaders from the class path, module path, and JDK itself.

- https://openjdk.org/jeps/486[JEP 486: Permanently Disable the Security Manager] - This proposal aims to phase out the Security Manager, which has been largely unused for securing client and server-side Java code, by removing the ability to enable it during runtime and revising the Java Platform specification to minimize its references. The changes will have minimal impact on most applications and tools, with the goal of improving JDK maintainability by reducing the complexity of resource-access decision delegation. The Security Manager API will be retained in this release to provide existing code maintainers time to migrate, with no intention of providing a replacement for its previous sandboxing or API interception functionalities.

- https://openjdk.org/jeps/490[JEP 490: ZGC: Remove the Non-Generational Mode] - The non-generational mode of the Z Garbage Collector (ZGC) will be removed to reduce the current maintenance cost of supporting two different modes as to speed up the development of new features.

== Candidate

N/A

== Preview

- https://openjdk.org/jeps/401[JEP 401: Value Classes and Objects] - Enhances the java platform with value objects, which are class instances that lack an object identity, and only have final fields. Popular classes that represent simple values in the JDK such as Integer will be migrated, and there'll be support for compatible migration of user-defined classes. This will help to improve the memory footprint, locality and GC efficiency.

- https://openjdk.org/jeps/478[JEP 478: Key Derivation Function API (Preview)
] - This proposal aims to introduce an API to derive additional keys from a secret key and other data through cryptographic algorithms as Key Derivation Functions (KDFs)

- https://openjdk.org/jeps/487[JEP 487: Scoped values (Fourth Preview)
] - Scoped values are being introduced as a preview API (fourth iteration) to enable methods to share immutable data both within threads and with child threads, offering better efficiency and clarity than thread-local variables, especially when used with virtual threads and structured concurrency.

- https://openjdk.org/jeps/488[JEP 488: Primitive Types in Patterns, instanceof, and switch (Second Preview)
] - This JEP first introduced as 455 returns without any changes. It aims to enhance pattern matching by allowing primitives in all pattern contexts, and allowing one to use them with instanceof and switch as well.

- https://openjdk.org/jeps/492[JEP 492: Flexible Constructor Bodies (Third Preview)
] - This proposed Java language feature allows statements before explicit constructor invocations, enabling more natural field initialization. As a preview feature in JDK 22 and 23, it introduces two constructor phases—a prologue and epilogue—to help developers place initialization logic more intuitively while preserving existing instantiation safeguards.

- https://openjdk.org/jeps/494[JEP 494: Module Import Declarations (Second Preview)
] - This will allow us to easily import all packages exported by a module, this facilitates the reuse of modular libraries without requiring the importing code to be within a module itself.

- https://openjdk.org/jeps/499[JEP 499: Structured Concurrency (Fourth Preview)
] - This is the fourth iteration of the JEP geared towards making concurrent programming easier to develop.

== Removed

N/A

== Lookahead

General availability of Java 25 is planned for September 2025, and while at the time of writing there are no JEPs targeted at it yet, we can already make some guesses based upon the submitted candidates and drafts.

Some of the ones I hope and expect to see land are:

* https://openjdk.org/jeps/495[JEP-495: Simple Source Files and Instance Main Methods (Fourth Preview)]- which aims to further enhance the onboarding experience

* https://openjdk.org/jeps/502[JEP-502: Stable Values (Preview)] - which would bring us immutable value holders that are at most initialized once

* https://openjdk.org/jeps/8340343[JEP draft 8340343: Structured Concurrency (Fifth Preview)] - structured concurrency has received quite a bit of feedback so far, so I hope to see it land, but we'll have to see

* https://openjdk.org/jeps/8326035[JEP draft 8326035: CDS Object Streaming] - proposes to add an object archiving mechanism for Class-Data Sharing (CDS) in the Z Garbage Collector (ZGC)

* https://openjdk.org/jeps/8300911[JEP draft 8300911: PEM API (Preview)] - introduces an easy-to-use API for encoding and decoding Privacy-Enhanded Mail (PEM) format.

