= Java 24
:toc:
:toc-placement:
:toclevels: 3

Java 24 will be released on the 18th of March 2025, and the full list of enhancements is now available tallying up to an astounding 24 changes. This certainly doesn't raise the expectations for release 25!

Let us take a closer look at what's awaiting us!

== Core

=== https://openjdk.org/jeps/472[JEP 472: Prepare to Restrict the Use of JNI]

This JEP is geared towards issuing warnings in a consistent manner in case of JNI or FFM usage that goes against https://openjdk.org/jeps/8305968[integrity by default].
These warnings and future restrictions can be selectively disabled by enabling those specific interfaces when needed.

When using a native function we'll get a `WARNING` at startup unless we use the JVM `--enable-native-access` option to authorize it, or add the `Enable-Native-Access` manifest entry.

Using native functions without authorization is illegal, hence the aptly called `--illegal-native-access` which allows us to control the JVM's behaviour, with the default being a warning.

The options are:

* warn (default): a warning will be emitted in the JVM logs
* allow: use is authorized without restriction
* deny: use is refused, an IllegalCallerException will be thrown

Violating this will result in a warning being emitted by the JVM in the following form:

`WARNING: A restricted method in java.lang.System has been called`

=== https://openjdk.org/jeps/484[JEP 484: Class-File API]

This JEP which was initially a preview in 22 and 23 aims to provide a standard API for parsing, generating and transforming Java class files.

It is geared towards helping developers handle the swifter release cadence, and thus class-file format changes. The API would evolve alongside the class file format, which would reduce the reliance of library and framework developers on third-party developers to update and test their class-file libraries. Frameworks and libraries making use the standard API will support class files from the latest JDK automatically.

=== https://openjdk.org/jeps/485[JEP 485: Stream Gatherers]

This JEP enhances the Stream API with new intermediate operations to facilitate new data operations that previously weren't easily achievable. This will be handled by facilitating the creation of custom intermediate operations to manipulate the streams, rather than a lot of new methods of the specifically requested functions.

We're already seeing some interesting libraries pop up with useful gatherers such as https://github.com/tginsberg/gatherers4j[Gatherers4j].

=== https://openjdk.org/jeps/489[JEP 489 Vector API (Ninth Incubator)]

The ninth iteration API of an API for vector computations. It aims to be a way to express these in a manner that compiles reliably to optimal vector instructions on supported CPU architectures to achieve better performance than equivalent scalar computations.

This iteration adds a new `Float16` which supports 16-bit variables in IEEE 754 binary16 format using the Vector API.

It has also been confirmed that the API will remain in incubation until project Valhalla enters preview itself so that the API can leverage the expected performance and in-memory representation enhancements.

=== https://openjdk.org/jeps/498[JEP 498: Warn upon Use of Memory-Access Methods in sun.misc.Unsafe]

A lot of low-level frameworks use the `Unsafe` class for faster memory access, however this class was always as an internal class and is officially unsupported and undocumented.

In "recent" releases we've received alternative methods to achieve the same thing, and as communicated when they were deprecated in JDK23 are slowly being phased out.

As of JDK 24 this will result in an `WARNING`, and in a future release the invocations will by default escalate to an exception.

The better approaches are:

==== https://openjdk.org/jeps/193[JEP 193: Variable Handles]

`VarHandle` landed in Java 9 and allows us a modern and type-safe way to handle variable access.

==== https://docs.oracle.com/en/java/javase/24/docs/api/java.base/java/lang/foreign/package-summary.html[Foreign Function & Memory API]

This API, also known as the FFM API landed in JDK 22 through https://openjdk.org/jeps/454[JEP 454] and allows us to safely interact with native memory and functions.

== HotSpot

=== https://openjdk.org/jeps/404[JEP 404: Generational Shenandoah (Experimental)]

This aims to enhance the Shenandoah GC with an experimental generational mode, without impacting non-generational.

With non-generational we mean that the heap was not split into multiple zones each containing objects of different ages. It's based upon the *Weak Generational Hypothesis* which stats that *most objects die young*. The collection of dead objects is very cheap, so if we separate the two we can target young objects to clean the heap more efficiently.

The intent is to reduce the sustained memory footprint, and reduce resource consumption. Initially it'll only support X64 and AArch64, with more instruction sets being supported later.

It was originally intended to land in JDK21. but it was dropped at that time due to identified risks (see for reference https://mail.openjdk.org/pipermail/jdk-dev/2023-June/007959.html[this jdk-dev mailing list entry]) to make sure than when it landed it would deliver the best possible result.

We can enable it through the following JVM options: `-XX:+UnlockExperimentalVMOptions -XX:ShenandoahGCMode=generational`.

=== https://openjdk.org/jeps/450[JEP 450: Compact Object Headers (Experimental)]

This enhancement was inspired by the experiments done in function of https://wiki.openjdk.org/display/lilliput[Project Lilliput] which found that many workloads have an average object size of 32 to 64 bytes.

It proposes to reduce the object header size in the HotSpot JvM from between 96 and 128 bits down to 64 bits on 64-bit architectures. An eye is also being kept on it not introducing any major throughput or latency overhead. It is disabled by default given its experimental nature to avoid unintended consequences.

=== https://openjdk.org/jeps/479[JEP 479: Remove the Windows 32-bit x86 Port]

As planned after the deprecation for removal in JDK 21 (JEP 449) the Windows 32 bit X86 bit source code and build support has been removed.

=== https://openjdk.org/jeps/490[JEP 490: ZGC: Remove the Non-Generational Mode]

The non-generational mode of the Z Garbage Collector (ZGC) will be removed to reduce the current maintenance cost of supporting two different modes as to speed up the development of new features.

=== https://openjdk.org/jeps/491[JEP 491: Synchronize Virtual Threads without Pinning]

To provide some context for this JEP: Virtual Threads are lightweight threads managed by the JVM, designed to have minimal overhead compared to traditional platform threads. They are particularly well-suited for I/O-bound or highly concurrent applications, as they enable efficient scaling without the resource constraints associated with platform threads. When executed, virtual threads are mounted onto platform threads (also called carrier threads), with the JVM handling scheduling and context switching. This abstraction simplifies concurrent programming by reducing the need for complex thread-pooling or asynchronous programming constructs. Virtual threads were introduced as part of https://openjdk.org/projects/loom/[Project Loom] and formalized in https://openjdk.org/jeps/444[JEP 444].

An issue up until now is that Java synchronization didn't unmount the platform thread, thus the platform thread was *pinned* to the virtual thread which negatively impacted the scalability of virtual threads.

This JEP aims to resolve this issue by making it possible for Virtual Threads that block in such cases to release their underlying platform threads. This will almost fully eliminate cases of VT being pinned to platform threads and resolve one of the most frequently encountered performance issue when adapting them.

=== https://openjdk.org/jeps/501[JEP 501: Deprecate the 32-bit x86 Port for Removal]

The final remaining 32-bit x86 port which is the one for Linux is being deprecated, and thus all downstream ones. After the 32-bit x86 port is removed, the only way to run Java programs on 32-bit x86 processors will be the architecture-agnostic https://openjdk.org/projects/zero/[Zero] port of the JDK.

== Language specification

=== https://openjdk.org/jeps/488[JEP 488: Primitive Types in Patterns, instanceof, and switch (Second Preview)]

This JEP first introduced as 455 returns without any changes. It aims to enhance pattern matching by allowing primitives in all pattern contexts, and allowing one to use them with instanceof and switch as well.

=== https://openjdk.org/jeps/492[JEP 492: Flexible Constructor Bodies (Third Preview)]

This proposed Java language feature allows statements before explicit constructor invocations, enabling more natural field initialization. As a preview feature in JDK 22 and 23, it introduces two constructor phases: a prologue and epilogue respectively to help developers place initialization logic more intuitively while preserving existing instantiation safeguards. This proposal has not changed compared to the second preview.

=== https://openjdk.org/jeps/494[JEP 494: Module Import Declarations (Second Preview)]

This will allow us to easily import all packages exported by a module, this facilitates the reuse of modular libraries without requiring the importing code to be within a module itself. For example: `import module java.base;`.

=== https://openjdk.org/jeps/495[JEP 495: Simple Source Files and Instance Main Methods (Fourth Preview)]

This preview which hasn't changed from it's previous iteration where it was known as `implicitly Declared Classes and Instance Main Methods,` would enable simplified programs by allowing them to be defined in an implicit class and an instance method `void main()`.

== Security

=== https://openjdk.org/jeps/478[JEP 478: Key Derivation Function API (Preview)]

This proposal aims to introduce an API to derive additional keys from a secret key and other data through cryptographic algorithms as Key Derivation Functions (KDFs).
KDF is part of the cryptographic standard  https://docs.oasis-open.org/pkcs11/pkcs11-spec/v3.1/os/pkcs11-spec-v3.1-os.html[PKCS #11], and are one of the key elements needed to implement Hybrid Public Key Encryption (HPKE). HPKE is a post-quantum cryptographic algorithm designed to be resistant to quantum computers.

=== https://openjdk.org/jeps/486[JEP 486: Permanently Disable the Security Manager]

The Security Manager, deprecated in Java 17, has now been permanently disabled in JDK 24 and is slated for complete removal in a future release. Originally designed to secure untrusted code (e.g., applets), the Security Manager provided a set of checks for actions like thread creation and file access. However, it was complex to maintain and had a significant performance footprint when enabled. Its removal has led to the deletion of over 14,000 lines of code, simplifying the JDK.

Opinions on the removal are divided. While most developers are unaffected, some platforms—particularly those with plugin systems like Kafka Connect, Elasticsearch, and Kestra—face challenges. These systems rely on executing untrusted code, and the Security Manager provided a built-in mechanism for enforcing security policies. Without it, developers must now implement alternatives such as sandboxing (e.g., Docker, GraalVM) or custom access controls using Java agents.

While modern security needs are better addressed by tools like containers and OS-level sandboxing, the transition away from the Security Manager requires effort and may not fully replicate its functionality for all use cases.

An interesting read on this topic is also: https://stuartmarks.wordpress.com/2024/12/12/detoxifying-the-jdk-source-code/[Stuart Marks - Detoxifying the JDK Source Code].

=== https://openjdk.org/jeps/496[JEP 496: Quantum-Resistant Module-Lattice-Based Key Encapsulation Mechanism]

JEP 496 introduces an implementation of the key encapsulation mechanism based on a quantum-resistant algorithm Module-Lattice (ML-KEM).These are used to secure symmetric keys over unsecured communication channels using public key cryptography.

Module-Lattice-Based Key Encapsulation Mechanism (ML-KEM), is a quantum-resistant algorithm standardized by NIST in https://csrc.nist.gov/pubs/fips/203/final[FIPS 203], to secure symmetric keys over unsecured channels using public key cryptography. It is designed to withstand attacks from future quantum computers, which could break current algorithms like RSA and Diffie-Hellman using https://www.wikiwand.com/en/articles/Shor's_algorithm[Shor's algorithm]. While quantum computers capable of such attacks are still far off (requiring thousands of Qubits, compared to today's ~64 Qubit systems), the transition to quantum-resistant algorithms is urgent to protect against "harvest now, decrypt later" threats.

This proposal integrates ML-KEM into Java's security APIs, thus providing implementations for:

* `KeyPairGenerator`
* `KEM`
* `KeyFactory`

And supporting three parameter sets:

* `ML-KEM-512`
* `ML-KEM-768`
* `ML-KEM-1024`

It also facilitates key generation and certificate signing via the keytool command.

This integration directly into the JDK enables a smooth adoption of quantum-resistant cryptography across all supported platforms, which will help future-proofing our applications against quantum computing threats. This aligns with https://www.nist.gov/[NIST]'s recommendation to transition to post-quantum algorithms within the next decade.

=== https://openjdk.org/jeps/497[JEP 497: Quantum-Resistant Module-Lattice-Based Digital Signature Algorithm]

JEP 497 introduces the Module-Lattice-Based Digital Signature Algorithm (ML-DSA), a quantum-resistant algorithm standardized by NIST in https://csrc.nist.gov/pubs/fips/204/final[FIPS 204], to enhance the security of Java applications. It is designed to withstand attacks from future quantum computers, which could break current algorithms like RSA and Diffie-Hellman using https://www.wikiwand.com/en/articles/Shor's_algorithm[Shor's algorithm]. While quantum computers capable of such attacks are still far off (requiring thousands of Qubits, compared to today's ~64 Qubit systems), the transition to quantum-resistant algorithms is urgent to protect against "harvest now, decrypt later" threats.

This proposal integrates ML-DSA into Java's security APIs, thus providing implementations for:

* `KeyPairGenerator`
* `KEM`
* `KeyFactory`

And supporting three parameter sets:

* `ML-DSA-44`
* `ML-DSA-65`
* `ML-DSA-87`

This integration directly into the JDK enables a smooth adoption of quantum-resistant cryptography across all supported platforms, which will help future-proofing our applications against quantum computing threats. This aligns with https://www.nist.gov/[NIST]'s recommendation to transition to post-quantum algorithms within the next decade.

== Tools

=== https://openjdk.org/jeps/493[JEP 493: Linking Run-Time Images without JMODs]

This aims to facilitate run-time image generate from modules regardless of what those modules were (JMOD, modular JAR, part of a previously linked run-time, etc.). This will also reduce the JDK size by enabling the jlink tool to create custom images without using the JDK's JMOD files. NOTE: this feature might not be enabled by all vendors.

== Targeted

- https://openjdk.org/jeps/475[JEP 475: Late Barrier Expansion for G1]  - Simplifies the G1 GC barrier implementation, which stores information about the application memory access by moving the expansion of the expansion thereof to later in the C2 JIT's compilation pipeline. This makes the G1 barriers more comprehensible, reduced the C2 execution time when using the G1 collector and guarantees the preservation of the C2 invariants while preserving the quality of C2 generated code.

== Integrated

- https://openjdk.org/jeps/483[JEP 483: Ahead-of-Time Class Loading & Linking] - This feature aims to enhance Java application startup performance by monitoring an application during one run and creating a cache of pre-loaded and pre-linked classes for subsequent runs. It seeks to improve startup time by leveraging the typically consistent startup process of applications, without requiring changes to application code, command-line usage, or build tools. The approach provides a foundation for future improvements in startup and warmup time, with the current implementation focusing on caching classes loaded by built-in class loaders from the class path, module path, and JDK itself.

== Preview

- https://openjdk.org/jeps/401[JEP 401: Value Classes and Objects] - Enhances the java platform with value objects, which are class instances that lack an object identity, and only have final fields. Popular classes that represent simple values in the JDK such as Integer will be migrated, and there'll be support for compatible migration of user-defined classes. This will help to improve the memory footprint, locality and GC efficiency.

- https://openjdk.org/jeps/487[JEP 487: Scoped values (Fourth Preview)
] - Scoped values are being introduced as a preview API (fourth iteration) to enable methods to share immutable data both within threads and with child threads, offering better efficiency and clarity than thread-local variables, especially when used with virtual threads and structured concurrency.

- https://openjdk.org/jeps/499[JEP 499: Structured Concurrency (Fourth Preview)
] - This is the fourth iteration of the JEP geared towards making concurrent programming easier to develop.

== Lookahead

General availability of Java 25 is planned for September 2025, and while at the time of writing there are no JEPs targeted at it yet, we can already make some guesses based upon the submitted candidates and drafts.

Some of the ones I hope and expect to see land are:

* https://openjdk.org/jeps/495[JEP-495: Simple Source Files and Instance Main Methods (Fourth Preview)]- which aims to further enhance the onboarding experience

* https://openjdk.org/jeps/502[JEP-502: Stable Values (Preview)] - which would bring us immutable value holders that are at most initialized once

* https://openjdk.org/jeps/8340343[JEP draft 8340343: Structured Concurrency (Fifth Preview)] - structured concurrency has received quite a bit of feedback so far, so I hope to see it land, but we'll have to see

* https://openjdk.org/jeps/8326035[JEP draft 8326035: CDS Object Streaming] - proposes to add an object archiving mechanism for Class-Data Sharing (CDS) in the Z Garbage Collector (ZGC)

* https://openjdk.org/jeps/8300911[JEP draft 8300911: PEM API (Preview)] - introduces an easy-to-use API for encoding and decoding Privacy-Enhanded Mail (PEM) format.

